apiVersion: v1
kind: Pod
metadata:
  name: pod-kube-news
spec:
  containers:
  - name: site
    image: jeanrnascimento/kube-news:v2
    ports:
    - containerPort: 8080
    env:
    - name: DB_DATABASE
      value: "kubenews"
    - name: DB_USERNAME
      value: "kubenews"
    - name: DB_PASSWORD
      value: "Pg#123"
    - name: DB_HOST
      value: "postgres"